// Auto-generated by Story Agent

import { detectFormat, renderText } from '../index';

describe('text-renderer-core', () => {
  describe('detectFormat', () => {
    it('should detect markdown', () => {
      const input = '# Heading';
      expect(detectFormat(input)).toBe('markdown');
    });

    it('should detect JSON', () => {
      const input = '{"key": "value"}';
      expect(detectFormat(input)).toBe('json');
    });

    it('should detect code', () => {
      const input = 'function foo() { return "bar"; }';
      expect(detectFormat(input)).toBe('code');
    });

    it('should detect plaintext', () => {
      const input = 'Hello, world!';
      expect(detectFormat(input)).toBe('plaintext');
    });
  });

  describe('renderText', () => {
    it('should render markdown', () => {
      const input = '# Heading';
      expect(renderText(input, 'markdown')).toMatch(/<h1[^>]*>Heading<\/h1>/);
    });

    it('should render JSON', () => {
      const input = '{"key": "value"}';
      expect(renderText(input, 'json')).toMatch(/<pre[^>]*>\{\s*"key"[^>]*\}<\/pre>/);
    });

    it('should render code', () => {
      const input = 'function foo() { return "bar"; }';
      expect(renderText(input, 'code')).toMatch(/<pre[^>]*>function foo\(\)/);
    });

    it('should render plaintext', () => {
      const input = 'Hello, world!';
      expect(renderText(input, 'plaintext')).toBe('<pre>Hello, world!</pre>');
    });
  });
});