-- Migration to add client_id to sa_security_audit table for multi-tenant reporting
ALTER TABLE public.sa_security_audit ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE public.sa_security_audit ADD COLUMN IF NOT EXISTS security_sensitivity_score INTEGER DEFAULT 0;
COMMENT ON COLUMN public.sa_security_audit.client_id IS 'The client organization ID associated with the audited operation.';
COMMENT ON COLUMN public.sa_security_audit.security_sensitivity_score IS 'Numerical score (0-100) generated by Uhura reflecting data risk.';