// Auto-generated by Story Agent

import DOMPurify from 'dompurify';

/**
 * Sanitizes and sandboxes code blocks to prevent XSS and code injection.
 * @param code The raw code block content
 * @returns Sanitized and sandboxed HTML
 */
export function sandboxCodeBlock(code: string): string {
  const sanitized = DOMPurify.sanitize(code, {
    ALLOWED_TAGS: ['pre', 'code'],
    ALLOWED_ATTR: ['class']
  });

  return `<iframe 
    sandbox="allow-same-origin" 
    srcdoc="${encodeURIComponent(sanitized)}"
    style="border: none; width: 100%;">
  </iframe>`;
}