// Auto-generated by Story Agent

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/*.test.ts'],
  moduleNameMapper: {
    '^@story-agent/text-renderer-core/(.*)$': '<rootDir>/$1'
  }
};