import 'dotenv/config';
import { writeFileSync, mkdirSync } from 'node:fs';
import { runMissionPipeline } from '../packages/mcp-server/src/lib/crew-mission-pipeline.js';
import { storeObservationMemory, storeCrewPersonalMemory, embeddingSource } from '../packages/shared/src/db.js';
(async () => {
const BRIEF = `Observation Lounge: our AWS Fargate deploy is TOO SLOW and FRAGILE — investigate and propose a STAGGERED, optimized deploy. Concrete pain points observed: (1) Every deploy REBUILDS both Docker images (MCP+UI) on the ARM runner even when ONLY terraform/infra changed — ~5-8 min wasted. (2) Adding a load_balancer block to the existing ECS service FORCES SERVICE REPLACEMENT (destroy+recreate), which is slow and fragile under our Fargate vCPU quota of 2 (rolling update needs old+new+UI=3 vCPU; we set min-healthy=0 as a workaround). (3) terraform apply waits for ECS service stable; if the new task fails its target-group health check the apply hangs/fails. (4) The whole pipeline is serial: build mcp → build ui → tf init → tf plan → tf apply. GOALS: stagger/parallelize so infra-only changes skip image builds; avoid ECS service replacement when adding target groups (separate concern: maybe register the agent endpoint via a NEW lightweight path on the EXISTING listener without a service-replacing load_balancer block — or use a sidecar/standalone agent service); parallelize the two image builds; split the workflow into independent jobs (build matrix + infra) with caching; make apply resilient (health-check grace, circuit breaker, rollback). Owners: Geordi(infra), Obrien(devops/CI), Data(arch), Quark(cost/time), Worf(security), Picard(command). Picard ends with an ORDERED, concrete optimization plan (what to change in deploy.yml + terraform) ranked by leverage. Terse, decisive.`;
const r = await runMissionPipeline(BRIEF);
const stamp = new Date().toISOString().slice(0,19).replace(/[:T]/g,'');
const md = ['# Observation Lounge — Deploy Optimization (stagger + speed)','',`**Date:** ${new Date().toISOString().slice(0,10)} | **Top model:** ${r.topModel} | **Cost:** $${r.efficiency.totalCostUSD}`,'','## Goals','',r.goals,'','## Contributions','',...r.contributions.flatMap(c=>[`### ${c.crewId} — \`${c.model}\` ($${c.costUSD})`,'',c.text,'']),'## Picard — optimization plan','',r.missionPlan,''].join('\n');
mkdirSync('docs/observation-lounge',{recursive:true});
const p=`docs/observation-lounge/deploy-optimization-${stamp}.md`; writeFileSync(p,md); console.log('TRANSCRIPT '+p);
const obs=await storeObservationMemory({storyId:'deploy-optimization',source:'mcp',transcript:{rounds:[{title:'deploy optimization',entries:r.contributions.map(c=>({speakerId:c.crewId,position:'support',statement:c.text,evidence:[c.model]}))}],consensusSummary:r.missionPlan,unresolvedRisks:['ECS service replacement on load_balancer change','vCPU quota 2 pending increase'],finalDecision:'approved',actionItems:['Stagger deploy.yml + terraform per plan']},tags:['deployment','cicd','optimization','fargate','terraform','staggered']});
console.log('OBS '+obs.id+' emb='+embeddingSource());
const m=await storeCrewPersonalMemory({crew_id:'obrien',memory_type:'decision_note',title:'Staggered/optimized Fargate deploy plan',content:r.missionPlan,tags:['deployment','cicd','optimization'],relates_to_crew:['geordi','data','quark','worf','picard']});
console.log('MEM '+m);
process.exit(0); // clean exit — work done; don't hang on open handles
})().catch(e=>{console.error('ERR',e?.message||e);process.exit(1);});
