import 'dotenv/config';
import { createHash } from 'crypto';
import { executeFullMissionLifecycle } from '@story-agent/mcp-server/lib/crew-coordinator.js';
import { crewAutonomyManager } from '@story-agent/mcp-server/lib/crew-autonomy-manager.js';
import { getDbClient, upsertStory } from '@story-agent/shared/db';
import { resolveRepository, branchExists, createBranch, createPullRequest } from '@story-agent/mcp-server/lib/github.js';
import { enforceWorfGateOutbound } from '@story-agent/mcp-server/lib/worfgate.js';

/**
 * Sovereign Factory - Master Execution Script
 * 
 * This script engages the 11-member crew to autonomously move a story
 * from discovery through architecture and into implementation generation.
 */
async function engage() {
  console.log('🛸 [SOVEREIGN FACTORY] ENERGIZING ALL PHASES...');
  console.log('========================================================');

  // 1. Start the passive autonomy monitor
  crewAutonomyManager.start();

  // 2. Discover pending missions for the project
  const clientId = process.env.TARGET_CLIENT_ID || 'bayer-int';
  const db = await getDbClient();
  
  console.log(`[PICARD] Discovering pending missions for client: ${clientId}...`);
  
  const { data: pendingStories, error } = await db
    .from('stories')
    .select('*')
    .eq('client_id', clientId)
    .eq('status', 'discovery')
    .order('story_id', { ascending: true });

  if (error) throw error;
  if (!pendingStories || pendingStories.length === 0) {
    console.log('[PICARD] No pending missions found in discovery. All systems nominal.');
    process.exit(0);
  }

  console.log(`[PICARD] ${pendingStories.length} missions discovered. Engaging sequence...`);

  for (const dbStoryRecord of pendingStories) {
    const currentRepo = dbStoryRecord.repo_full_name;
    const story = {
      id: dbStoryRecord.id,
      referenceNum: dbStoryRecord.story_id,
      name: dbStoryRecord.story_title,
      description: dbStoryRecord.notes || '',
      acceptanceCriteria: dbStoryRecord.acceptance_criteria || '',
      url: dbStoryRecord.story_url || '',
      workflowStatus: dbStoryRecord.status,
    };

    console.log(`\n🚀 [MISSION START] ${story.referenceNum}: ${story.name}`);
  console.log(`[DATA]   Calibrating architectural sensors...`);
  console.log(`[WORF]   Security perimeter at maximum readiness...`);

  // 3. Run the full autonomous loop
  const result = await executeFullMissionLifecycle({
    story,
    repoFullName: currentRepo,
    targetBranch: 'main',
    executionMode: 'autonomous',
    clientId,
    acceptanceCriteria: story.acceptanceCriteria,
    techStack: 'PostgreSQL, Supabase, TypeScript',
  });

  console.log('--------------------------------------------------------');
  console.log(`📡 MISSION STATUS: ${result.status.toUpperCase()}`);
  console.log(`💡 CONSENSUS: ${result.debate.consensusSummary}`);
  console.log(`📝 ACTION ITEMS: ${result.debate.actionItems.length} tasks identified.`);
  
  if (result.implementation) {
    console.log(`🛠️  IMPLEMENTATION: ${result.implementation.files.length} file(s) scaffolded.`);
    console.log(`🚀 [OBRIEN] Energizing delivery to GitHub...`);

    const { files } = result.implementation;
    const prTitle = `[${story.referenceNum}] ${story.name}`;
    const prBody = `## Mission: ${story.name}

${result.summary?.prBody || result.debate.consensusSummary}

### Implementation Notes
Autonomously generated by the Sovereign Factory crew.
Commit Message: ${result.summary?.commitMessage || 'No specific message generated.'}

### Consensus Action Items
${result.debate.actionItems.map(item => `- ${item}`).join('\n')}`;

    // 1. Security Check (WorfGate)
    const outboundPayload = [
      story.id,
      story.name,
      currentRepo,
      prTitle,
      prBody,
      ...files.map(f => `${f.path}\n${f.content}`),
    ].join('\n\n');

    enforceWorfGateOutbound({
      target: 'github',
      payloadText: outboundPayload,
      repoFullName: currentRepo,
      clientId,
      securitySensitivityScore: result.securitySensitivityScore,
      operation: 'engage_sovereign_factory_delivery',
    });

    // 2. Prepare Repository & Branch
    const repo = await resolveRepository(currentRepo);
    // Implementation: Scoped branching for monorepo isolation
    const branchName = `client/${clientId}/${repo.name}/${story.referenceNum.toUpperCase()}`;
    const exists = await branchExists(repo, branchName);
    if (!exists) await createBranch(repo, branchName);

    // 3. Commit Files via GitHub API
    const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? '';
    const committedPaths: string[] = [];

    for (const file of files) {
      const url = `https://api.github.com/repos/${repo.fullName}/contents/${encodeURIComponent(file.path)}`;
      const existing = await fetch(url, {
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      });
      const existingSha = existing.ok ? ((await existing.json() as any).sha as string | undefined) : undefined;

      const body = {
        message: result.summary?.commitMessage ? `${story.referenceNum}: ${result.summary.commitMessage}` : file.message,
        content: Buffer.from(file.content, 'utf-8').toString('base64'),
        branch: branchName,
        sha: existingSha,
      };

      const res = await fetch(url, {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      if (!res.ok) {
        throw new Error(`Failed to commit ${file.path}: ${res.status} ${await res.text()}`);
      }
      committedPaths.push(file.path);
    }

    // 4. Open Pull Request
    const pr = await createPullRequest({
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: repo.defaultBranch,
    });

    // 5. Update Record in Supabase
    // Generate a deterministic UUID based on story reference for idempotent upserts
    const deterministicId = createHash('sha256').update(`${repo.fullName}:${story.referenceNum}`).digest('hex').substring(0, 36);
    await upsertStory(dbStoryRecord.client_id, {
      id: deterministicId,
      storyId: story.referenceNum,
      storyTitle: story.name,
      storyUrl: story.url,
      repoFullName: repo.fullName,
      branch: branchName,
      baseBranch: repo.defaultBranch,
      status: 'pr_open',
      prNumber: pr.number,
      prUrl: pr.url,
      prStatus: 'open',
      phase: 1,
      acceptanceCriteria: story.acceptanceCriteria,
      notes: `Autonomously delivered by engage-sovereign-factory script. Files: ${committedPaths.join(', ')}`,
    });

    console.log(`✅ [MISSION DELIVERED] Pull Request opened: ${pr.url}`);
    result.status = 'delivered';
  }
  }

  console.log('========================================================');
  console.log('✨ Mission Phase Complete. The crew remains on station.');

  // Keep process alive briefly for any background audit logging to finish
  setTimeout(() => {
    crewAutonomyManager.stop();
    process.exit(0);
  }, 2000);
}

engage().catch(err => {
  console.error('❌ CRITICAL SYSTEM FAILURE:', err);
  process.exit(1);
});