#!/usr/bin/env bash
# Generate and install the two OAuth 2.1 secrets (packages/mcp-server/src/agent-core/oauth-provider.ts)
# — locally (~/.alexai-secrets, same convention every other secret in this repo uses) AND into the
# live story-agent/runtime AWS Secrets Manager secret the ECS task actually reads at boot
# (terraform/ecs.tf's local.runtime_secrets — both keys are wired there already).
#
# DELIBERATELY NOT run by CI/WorfGate automatically. STORY_AGENT_OAUTH_OWNER_PASSPHRASE has to be a
# value the human operator (you) actually knows — it's what you type into the browser consent screen
# during your own OAuth authorization — so it has to be generated by, and visible to, you. Same
# reasoning for the signing key: nobody should be able to point at "the system" as the origin of the
# credential that makes every future token trustworthy.
#
# story-agent/runtime is a SHARED secret (CREW_LLM_APPROVED_KEY, SUPABASE_CLOUD_URL,
# SUPABASE_CLOUD_KEY already live there) — AWS's put-secret-value REPLACES the entire secret string,
# so this script reads the current value first and merges the two new keys in via jq, rather than
# clobbering everything else in that secret.
#
# Usage:  zsh -ic 'bash scripts/setup-oauth-secrets.sh [--force]'
#   --force   Regenerate even if both secrets are already set locally (invalidates every
#             outstanding OAuth token issued so far — anyone already connected has to reauthorize).
set -euo pipefail

SECRET_NAME="${STORY_AGENT_RUNTIME_SECRET_NAME:-story-agent/runtime}"
SECRETS_DIR="$HOME/.alexai-secrets"
SECRETS_FILE="$SECRETS_DIR/api-keys.env"
FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true

say() { echo "🛰️  $1"; }
fail() { echo "❌ $1" >&2; exit 1; }

command -v openssl >/dev/null 2>&1 || fail "openssl not found (should ship with macOS)."
command -v aws >/dev/null 2>&1 || fail "aws CLI not found. Install + 'aws configure' first."
command -v jq >/dev/null 2>&1 || fail "jq not found (brew install jq)."
aws sts get-caller-identity >/dev/null 2>&1 || fail "AWS credentials not configured/authorized."

mkdir -p "$SECRETS_DIR"
touch "$SECRETS_FILE"

# ── Idempotency guard ──────────────────────────────────────────────────────
if ! $FORCE && grep -q '^export STORY_AGENT_OAUTH_SIGNING_KEY=' "$SECRETS_FILE" 2>/dev/null \
   && grep -q '^export STORY_AGENT_OAUTH_OWNER_PASSPHRASE=' "$SECRETS_FILE" 2>/dev/null; then
  say "Both secrets already present in $SECRETS_FILE — leaving them as-is."
  say "Pass --force to regenerate (this invalidates every outstanding OAuth token — anyone already"
  say "connected, including any live Claude.ai session, would need to reauthorize)."
  exit 0
fi

if $FORCE; then
  echo "⚠️  --force: regenerating both secrets. Every previously-issued access/refresh token will" >&2
  echo "   stop verifying the moment this deploys — this is NOT graceful for anyone mid-session." >&2
  printf "Continue? [y/N] "
  read -r REPLY
  [[ "$REPLY" =~ ^[Yy]$ ]] || { say "cancelled"; exit 0; }
fi

# ── Generate ─────────────────────────────────────────────────────────────
SIGNING_KEY="$(openssl rand -base64 48)"
OWNER_PASSPHRASE="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)"  # URL/form-safe, no punctuation to fumble typing/pasting

# ── 1. Local (~/.alexai-secrets) — same convention as setup-app-bucket.sh's STORY_AGENT_S3_BUCKET ──
for KV in "STORY_AGENT_OAUTH_SIGNING_KEY=$SIGNING_KEY" "STORY_AGENT_OAUTH_OWNER_PASSPHRASE=$OWNER_PASSPHRASE"; do
  KEY="${KV%%=*}"
  if grep -q "^export ${KEY}=" "$SECRETS_FILE" 2>/dev/null; then
    perl -i -pe "s{^export ${KEY}=.*}{export ${KV}}" "$SECRETS_FILE"
  else
    { echo ""; echo "# OAuth 2.1 authorization endpoint (scripts/setup-oauth-secrets.sh) — do not hand-edit,"; echo "# re-run the script (--force) to rotate."; echo "export ${KV}"; } >> "$SECRETS_FILE"
  fi
done
say "wrote both secrets to $SECRETS_FILE"

# ── 2. Live AWS Secrets Manager — read-merge-write, story-agent/runtime is shared with other keys ──
if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" >/dev/null 2>&1; then
  CURRENT="$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text)"
else
  CURRENT='{}'
fi

MERGED="$(echo "$CURRENT" | jq --arg sk "$SIGNING_KEY" --arg pp "$OWNER_PASSPHRASE" \
  '. + {STORY_AGENT_OAUTH_SIGNING_KEY: $sk, STORY_AGENT_OAUTH_OWNER_PASSPHRASE: $pp}')"

if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" >/dev/null 2>&1; then
  aws secretsmanager put-secret-value --secret-id "$SECRET_NAME" --secret-string "$MERGED" >/dev/null
  say "updated '$SECRET_NAME' (new version) — merged in, existing keys untouched"
else
  aws secretsmanager create-secret --name "$SECRET_NAME" \
    --description "Story Agent — shared runtime credentials (LLM key, Supabase, OAuth signing/passphrase)" \
    --secret-string "$MERGED" >/dev/null
  say "created '$SECRET_NAME' with both new keys"
fi

echo ""
echo "🎉 Done. STORY_AGENT_OAUTH_SIGNING_KEY and STORY_AGENT_OAUTH_OWNER_PASSPHRASE are set locally"
echo "   and in AWS Secrets Manager ('$SECRET_NAME')."
echo ""
echo "   Your consent-screen passphrase (you'll need to paste this into the browser during the"
echo "   Claude.ai connector setup — save it somewhere you can get back to):"
echo ""
echo "   ${OWNER_PASSPHRASE}"
echo ""
echo "   Next: the ECS task already reads both keys from this secret (terraform/ecs.tf's"
echo "   local.runtime_secrets) — no task definition change needed, but the RUNNING task won't see"
echo "   the new values until it restarts. Either wait for the next deploy, or force one now:"
echo "     aws ecs update-service --cluster <cluster> --service <service> --force-new-deployment"
